### ISSUE TITLE
Close Tab Issue

### ISSUE THREAD

**Issue by ItsJordan** [kurisubrooks/glass2#10]
When closing a tab it doesn't switch to a different one like a typical browser and it also leaves the previous URL in the search bar

![GIF of Issue](https://i.imgur.com/TrjRthI.gif)

**Comment by KatieIsAKitty** [comment]
possible to fix with an addition to the close func that sets the active tab to` this.tabs.first()`

**Comment by kurisubrooks** [comment]
Fixed in 3592ab3b485635e7298e51f4a13c40959015af8e
