### ISSUE TITLE
IP addresses not recognized in the address bar

### ISSUE THREAD

**Issue by KatieIsAKitty** [kurisubrooks/glass2#14]
`https://www.google.com.au/search?q=192.168.1.1&cad=h`
Says it all.

**Comment by craigmc08** [comment]
Currently rewriting the url validation. I'm going to base it off of Chromium's urlbar, but I am still searching the source for it.

**Comment by craigmc08** [comment]
Fixed in e45abbdec132089e9854e4186a8331cf7a293f00
