### ISSUE TITLE
Ctrl+W kills process

### ISSUE THREAD

**Issue by KatieIsAKitty** [kurisubrooks/glass2#15]
(my) Intended behaviour is that ctrl+w will close the current tab/application. Instead kills the entire window.
not sure if we can fix this due to the fact that we run inside a browser but leaving this here in case someone does this.

**Comment by HorizonTM** [comment]
💯

**Comment by craigmc08** [comment]
It is possible to change this. The window menu (hidden in this case) is what causes this. Since we aren't using the window menu, we can just set it to null and then add our own ctrl+w stuff. https://electron.atom.io/docs/api/browser-window/#winsetmenumenu-linux-windows

**Comment by kurisubrooks** [comment]
In my fix, I just disabled the keybind whilst the window is open. Feel free to modify it if you want to change that functionality

Btw; could you add me on Discord please? (Kurisu#7700)
