### ISSUE TITLE
Browser Close Button Issues

### ISSUE THREAD

**Issue by ItsJordan** [kurisubrooks/glass2#7]
When you hover over the X (close button) in the browser, at least, it has an odd shape and the colour change can't be seen on your current tab.

![GIF of Issue](https://i.imgur.com/1Y98xXa.gif)

**Comment by KatieIsAKitty** [comment]
the X will be centered better in the browser dark theme PR, shape is still a bit of an 'egg'

**Comment by ItsJordan** [comment]
Did you fix the colours too?

**Comment by KatieIsAKitty** [comment]
Haven't touched light theme stuff except position. I'll see about changing it to be brighter on the current tab

**Comment by kurisubrooks** [comment]
Fixed in 460de9a
